### ISSUE TITLE
Does it works with cpu too?

### ISSUE THREAD

**Issue by andreae293** [Jack000/glid-3-xl-stable#7]
Hi, has anyone ever tried to train with cpu?
i know it will be super slow but im tried for the fun of it

i currently disabled my gpu by setting this line in image_train_stable.py
torch.cuda.is_available = lambda : False

but then in hangs forever in load_data:

> 
> creating model and diffusion...
> total base parameters 859520964
> creating data loader...
> training...
> loading model for the first time, will ignore missing layers if possible
> 
> Traceback (most recent call last):
>   File "scripts\image_train_stable.py", line 157, in <module>
>     main()
>   File "scripts\image_train_stable.py", line 85, in main
>     TrainLoop(
>   File "c:\users\andre\desktop\ml\glid-3\guided_diffusion\train_util.py", line 193, in run_loop
>     batch, cond = next(self.data)
>   File "scripts\image_train_stable.py", line 111, in load_latent_data
>     for batch, model_kwargs, text in data:
>   File "c:\users\andre\desktop\ml\glid-3\guided_diffusion\image_text_datasets.py", line 66, in load_data
>     yield from loader
>   File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
>     data = self._next_data()
>   File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\torch\utils\data\dataloader.py", line 1196, in _next_data
>     self._shutdown_workers()
>   File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\torch\utils\data\dataloader.py", line 1322, in _shutdown_workers
>     w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
>   File "C:\Users\andre\anaconda3\envs\ldm\lib\multiprocessing\process.py", line 149, in join
>     res = self._popen.wait(timeout)
>   File "C:\Users\andre\anaconda3\envs\ldm\lib\multiprocessing\popen_spawn_win32.py", line 108, in wait
>     res = _winapi.WaitForSingleObject(int(self._handle), msecs)
> KeyboardInterrupt
> 

sorry for bothering with useless question but am i doing something wrong?
thanks

**Comment by timotheecour4** [comment]
@andreae293 can you please provide more details?
I tried:
```
export CUDA_VISIBLE_DEVICES=-1
MODEL_FLAGS="--actual_image_size 512 --lr_warmup_steps 10000 --ema_rate 0.9999 --attention_resolutions 64,32,16 --class_cond False --diffusion_steps 1000 --image_size 64 --learn_sigma False --noise_schedule linear --num_channels 320 --num_heads 8 --num_res_blocks 2 --resblock_updown False --use_fp16 False --use_scale_shift_norm False "
TRAIN_FLAGS="--lr 5e-5 --batch_size 32 --log_interval 10 --save_interval 5000 --kl_model kl.pt --resume_checkpoint diffusion.pt"
export OPENAI_LOGDIR=./logs/
python scripts/image_train_stable.py --data_dir /path/to/image-and-text-files $MODEL_FLAGS $TRAIN_FLAGS
```
where I change the default from README from `--use_fp16 True` to `--use_fp16 False` (and IIUC no need to remove .half() from the image_train_stable.py with this flag), but it gives:

RuntimeError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 0; 15.78 GiB total capacity; 10.52 GiB already allocated; 3.86 GiB free; 10.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

ie, still seems to use gpu instead of cpu

**Comment by ghost** [comment]
Stable Diffusion requires CUDA to run the AI, as it is the language for communicating with the GPU and preforming the necessary  calculations. Using with the CPU would require a complete rewrite or virtualization which requires more RAM and money than it would take to go and buy a supported CUDA GPU. Although if anyone who is reading this is willing, would it be possible to utilize a TPU from Kaggle or Google Collab instead? I feel like it might be more efficient than a GPU or CPU, as it is meant for processing Tensors directly.

**Comment by andreae293** [comment]
@timotheecour4 sorry for the late response
 if you dont have enough RAM you have to dedicate a lot of GB to the virtual memory (paging file or swap memory)
i dont know the minimum required by this repo,but i did dedicate 100 GB of virtual memory
also if you are trying to finetune i suggest you to look for dreambooth for stable diffusion

@TheRealUnBot stable diffusion does not necessarily requires CUDA-supporting hardware to run
since its based on pytorch you can run just fine in CPU with the downside of being x50 slower
